### ISSUE TITLE
cornerstore-core & Node.js File System: loadImage method error

### ISSUE THREAD

**Issue by PierreLeGuen** [cornerstonejs/cornerstone#435]
Version: cornerstone-core 2.3.0

Using cornerstoneWADOImageLoader and fs
`const imageId = cornerstoneWADOImageLoader.wadouri.fileManager.add(filePath); 
`
Here filePath looks like: **/home/path_to_dcms/my.dcm**, and imageId is good. (dicomfile:0)

Now when cornerstone.loadImage(imageId) is called I get : 
`"Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'."`

This is due to:

```
function getImageLoadObject(imageId) {
...
return cachedImage.imageLoadObject; // breaks here
}
```

Any hints appreciated, does loadImage supports Node.js File System ?

**Comment by dannyrb** [comment]
Are you able to provide a reproduction or steps to reproduce this issue? I know several users leverage CornerstoneWADOImageLoader with node. I'm unsure of the particular issue you're describing.

**Comment by PierreLeGuen** [comment]
Indeed the problem was that CornerstoneWADOImageLoader needed to be leveraged with node. Creating an ImageLoader that supports electron and fs for CornerstoneWADOImageLoader made it work. Thank you

**Comment by wjc13753** [comment]
Hi, Pierre LE GUEN! I encountered the same problem with using cornerstone with electron:
I already get the ImageID which is "dicomfile:0" and call "cornerstone.loadImage(imageId)", then is shows:

TypeError: Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'.
    at D:\SubtleMedical\electrontest\Try\node_modules\cornerstone-wado-image-loader\dist\cornerstoneWADOImageLoader.js:6129:16
    at new Promise (<anonymous>)
    at loadFileRequest (D:\SubtleMedical\electrontest\Try\node_modules\cornerstone-wado-image-loader\dist\cornerstoneWADOImageLoader.js:6120:10)
    at Object.load (D:\SubtleMedical\electrontest\Try\node_modules\cornerstone-wado-image-loader\dist\cornerstoneWADOImageLoader.js:5789:26)
    at loadImage (D:\SubtleMedical\electrontest\Try\node_modules\cornerstone-wado-image-loader\dist\cornerstoneWADOImageLoader.js:6281:88)
    at loadImageFromImageLoader (D:\SubtleMedical\electrontest\Try\node_modules\cornerstone-core\dist\cornerstone.js:3365:25)
    at Module.loadImage (D:\SubtleMedical\electrontest\Try\node_modules\cornerstone-core\dist\cornerstone.js:3402:10)
    at EventEmitter.<anonymous> (file:///D:/SubtleMedical/electrontest/Try/firesale-chapter-4/app/renderer.js:54:15)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:114:818)

Could you please tell me how you leveraged CornerstoneWADOImageLoader to fix the problem? Thank you very much!

**Comment by PierreLeGuen** [comment]
Hi, you can use my fork [PierreLeGuen/cornerstoneFSImageLoader](https://github.com/PierreLeGuen/cornerstoneFSImageLoader) (quite outdated), or check the branch diff: [cornerstoneWADOImageLoader/compare/master...PierreLeGuen:master](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/compare/master...PierreLeGuen:master)
